const actions = {
  SET_USER: "SET_USER",
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_DISOVER_WEEKLY: "SET_DISOVER_WEEKLY",
  SET_ITEM: "SET_ITEM",
  SET_PLAYING: "SET_PLAYING",
  SET_TOP_ARTISTS: "SET_TOP_ARTISTS",
};

export default actions;
